name: Scheduled Task

on:
  workflow_dispatch:  # 手動実行を有効化
  schedule:
    - cron: "0 * * * *"  # 毎時00分に実行

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリを取得
        uses: actions/checkout@v3
      
      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: gitをインストールする
        run: |
          sudo apt-get install -y git

      - name: リポジトリをクローンする
        run: |
          git clone https://github.com/mshrynzw/be-side_your_life-new_hp.git

      - name: Pythonをセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: blogフォルダを作成する
        run: |
          mkdir ./blog/

      - name: 依存関係をインストール
        run: |
          pip install -r requirements.txt
        working-directory: .

      - name: スクリプトを実行
        run: |
          python src/main.py
        working-directory: .

      - name: ブログをコピーする
        run: |
          cp -r ./blog/* be-side_your_life-new_hp/data/blog/blog/

      - name: 変更をコミットしてプッシュ
        run: |
          cd be-side_your_life-new_hp
          echo "Current directory: $(pwd)"
          echo "Files to be committed:"
          git status
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/blog/blog/*
          echo "After git add:"
          git status
          git commit -m "Update blog content [skip ci]"
          echo "After git commit:"
          git status
          git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/mshrynzw/be-side_your_life-new_hp.git
          git push
          echo "After git push:"
          git status
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}