name: Scheduled Task

on:
  schedule:
    - cron: "0 * * * *"  # 毎時00分に実行

jobs:
  run-script:
    runs-on: ubuntu-latest  # 実行環境（Ubuntu）
    steps:
      - name: リポジトリを取得
        uses: actions/checkout@v3  # リポジトリのコードを取得

      - name: Pythonをセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"  # 最新のPython 3系を使用

      - name: 依存関係をインストール
        run: |
          pip install -r requirements.txt  # 依存ライブラリをインストール（必要なら）
        working-directory: src  # srcフォルダ内で実行

      - name: スクリプトを実行
        run: |
          python main.py  # スクリプトを実行
        working-directory: src  # srcフォルダ内で実行
