name: Scheduled Task

on:
  workflow_dispatch:  # 手動実行を有効化
  schedule:
    - cron: "0 * * * *"  # 毎時00分に実行

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリを取得
        uses: actions/checkout@v3
      
      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Pythonをセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: 依存関係をインストール
        run: |
          pip install -r requirements.txt
        working-directory: .

      - name: スクリプトを実行
        run: |
          python src/main.py
        working-directory: .
